### ISSUE TITLE
get.exe fails - no response

### ISSUE THREAD

**Issue by awtrekka** [Heltec-Aaron-Lee/WiFi_Kit_series#104]
When I try to run get.exe, it fails
please advise how to proceed.
thanks
Andrew

C:\Users\Andrew Wells\heltec\esp32\tools>get
System: Windows, Info: Windows-10-10.0.18362
Platform: i686-mingw32
Downloading xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip
Traceback (most recent call last):
  File "get.py", line 139, in <module>
    sys_name = 'Windows'
  File "get.py", line 89, in get_tool
    print('Downloading ' + archive_name)
  File "site-packages\requests\api.py", line 70, in get
  File "site-packages\requests\api.py", line 56, in request
  File "site-packages\requests\sessions.py", line 488, in request
  File "site-packages\requests\sessions.py", line 609, in send
  File "site-packages\requests\adapters.py", line 473, in send
requests.exceptions.ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Failed to execute script get

C:\Users\Andrew Wells\heltec\esp32\tools>

**Comment by Heltec-Aaron-Lee** [comment]
Mostly, that's a network problem, can you try again or try the get.py?
