### ISSUE TITLE
Python2 EOL

### ISSUE THREAD

**Issue by terrancewong** [Heltec-Aaron-Lee/WiFi_Kit_series#148]
Please upgrade to python3

**Comment by Patronics** [comment]
This is causing compiling even empty code to completely fail on MacOS at this point, with errors like

```
Arduino: 1.8.19 (Mac OS X), Board: "WiFi LoRa 32(V2), 240MHz (WiFi/BT), 921600, None, REGION_EU868, CUSTOM, None"


Traceback (most recent call last):
  File "esptool.py", line 57, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports.py", line 29, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_posix.py", line 31, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_osx.py", line 32, in <module>
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
Failed to execute script esptool
exit status 255
/Applications/Arduino.app/Contents/Java/arduino-builder returned 255
Error compiling for board WiFi LoRa 32(V2).

```
